### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by NicoGonzalez94** [FT-Key/RollingVet#31]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/user-attachments/assets/4ccd030e-a7cd-42c1-86cc-686524593fdd)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by FT-Key** [comment]
Listo, se eliminarion comentarios innecesarios y se mantuvieron solo aquellos donde el código es poco intuitivo o donde ayuda amanterner el código ordenado
