### ISSUE TITLE
Turnos

### ISSUE THREAD

**Issue by NicoGonzalez94** [FT-Key/RollingVet#32]
## Proceso

1. Ingrese a la pagina.
2. Me registre con un usuario.
3. Quise agendar un turno.

## Resultado esperado

• Poder sacar turno sin problemas.

## Resultado actual

• Al momento de querer agendar un turno me pide que ingrese un horario, pero no hay un espacio para poner un horario.

## Captura

![image](https://github.com/user-attachments/assets/a2f1d4be-b5ff-49f8-b325-c1405a775179)
![image](https://github.com/user-attachments/assets/8d509a1b-5c84-4d50-b90a-3f52c5592bdf)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by FT-Key** [comment]
No se podrá reservar un turno a menos que un admin habilite los turnos para esa semana
