### ISSUE TITLE
Consola

### ISSUE THREAD

**Issue by NicoGonzalez94** [FT-Key/RollingVet#33]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.

## Resultado esperado

• Que no se muestre informacion por consola.

## Resultado actual

• Se muestra informacion por consola.

## Captura

![image](https://github.com/user-attachments/assets/730c7091-1004-46bb-af29-ab0fc0528c02)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by FT-Key** [comment]
Solucionado!
